services:
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_PORT:-6379}:6379'
      - '8001:8001'
    volumes:
      - redis-stack:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-h', 'localhost', 'ping']
      interval: 1m
      timeout: 10s
      retries: 5

  app:
    depends_on:
      mysql:
        condition: service_healthy
      redis-stack:
        condition: service_healthy
    build: .
    env_file:
      - .env
    restart: on-failure
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true

volumes:
  db-data:
  redis-stack:
