CREATE DATABASE IF NOT EXISTS voting DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'voter'@'%' IDENTIFIED BY 'voting';
GRANT ALL PRIVILEGES ON voting.* TO 'voter'@'%';
FLUSH PRIVILEGES;
